version: "3.7"

services:
  app_proxy:
    depends_on:
      - web
    environment:
      # Always point to the standard container name
      APP_HOST: ${APP_ID}_web_1
      # pgAdmin listens on 80 inside; Umbrel exposes host port from manifest
      APP_PORT: 80

  db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_DB: umbrel
      POSTGRES_USER: umbrel
      POSTGRES_PASSWORD: change_me
      TZ: America/Chicago
    volumes:
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umbrel -d umbrel"]
      interval: 10s
      timeout: 5s
      retries: 5

  web: # pgAdmin
    image: dpage/pgadmin4:8
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Use explicit values; Umbrel doesn't inject APP_DEFAULT_* into compose
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: change_me
      PGADMIN_LISTEN_PORT: "80"

      # Reverse-proxy fixes (trust one proxy hop)
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: "0"

      TZ: America/Chicago
    volumes:
      - ${APP_DATA_DIR}/pgadmin:/var/lib/pgadmin
      # If you want auto-registration later, drop servers.json in APP_DATA_DIR and uncomment:
      # - ${APP_DATA_DIR}/servers.json:/pgadmin4/servers.json:ro

