version: "3.7"

services:
  app_proxy:
    environment:
      # Route Umbrel's proxy to the web service
      APP_HOST: ${APP_ID}_web_1
      APP_PORT: 5050

  db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_DB: umbrel
      POSTGRES_USER: umbrel
      POSTGRES_PASSWORD: change_me
      TZ: America/Chicago
    volumes:
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umbrel -d umbrel"]
      interval: 10s
      timeout: 5s
      retries: 5

  web: # pgAdmin
    image: dpage/pgadmin4:8
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${APP_DEFAULT_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${APP_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: "80"

      # Fix login/blank page behind Umbrel's reverse proxy (trust one proxy hop)
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: "0"

      TZ: America/Chicago
    volumes:
      - ${APP_DATA_DIR}/pgadmin:/var/lib/pgadmin
      - ${APP_DIR}/servers.json:/pgadmin4/servers.json:ro

