version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: umbrel-store-hello_web_1
      APP_PORT: 80
      APP_PROTOCOL: http
      PROXY_AUTH_ADD: "false"

  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./site:/usr/share/nginx/html:ro
    expose:
      - "80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:80/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

